[package]
name = "daedalus"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = { version = "1.0", features = ["spin_no_std"] }
spin = "0.5.2"

[[bin]]
name = "daedalus"
test = false
bench = false
