[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "aarch64-daedalus.json"

[target.aarch64-daedalus]
rustflags = [
    "-C", "link-arg=-Tlinker.ld",
]
runner = "./scripts/qemu-runner.sh"